name: parrot_trainer
description: A PWA application for shaping behavior in parrots.

version: 1.0.0+1

environment:
  sdk: ">=2.14.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  provider: ^6.0.1
  soundpool: ^2.2.0-nullsafety.0
  dart_json_mapper: ^2.1.17

dev_dependencies:
  build_runner:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - assets/

